language: c
before_script:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ocaml41+opam11
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam
  - export OPAMYES=1
  - opam init
  - eval `opam config env`
  - opam install oasis
  - opam install core omd re yojson ounit ocamlfind
  - oasis setup
  - ocaml setup.ml -configure
script:
  - ocaml setup.ml -build
  - ocaml setup.ml -test
